:command! Vrc e ~/.vimrc
:command! Nrc e ~/.config/nvim/init.vim
:command! Brc e ~/.bashrc
:command! Zrc e ~/.zshrc
:command! Zenv e ~/.zshenv
:command! Arc e ~/.config/alacritty/alacritty.yml
:command! Irc e ~/.install_dependencies
:command! Grc e ~/.gitconfig
:command! Trc e ~/.tmux.conf
:command! Vsc e ~/.config/nvim/coc-settings.json
