#!/bin/bash

# Interactice Shells {{{
case $- in
  *i*) ;;
  *) return ;;
esac
#}}}

export FLYCTL_INSTALL="/home/jrasmusbm/.fly"
export DOTFILES="$HOME/dotfiles"
export plug="$DOTFILES/vim/pack/bundle/opt"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$DOTFILES/bin"
export PATH="$HOME/.pyenv/bin:$PATH"

# Aliases
alias q="exit"
# alias \$=""
alias so="source"
alias ac="source ./.venv/bin/activate"
alias ls="my-ls"
alias grep='my-grep'
alias da="deactivate"
alias cdr='cd `cd-root`'
alias ..="cd .."
alias 2..="cd ../.."
alias 3..="cd ../../.."
alias 4..="cd ../../../.."
alias 5..="cd ../../../../.."

# History {{{
shopt -s histappend

HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
#}}}

set -o vi

shopt -s checkwinsize
shopt -s globstar

test -x "/usr/bin/lesspipe" && eval "$(SHELL=/bin/sh lesspipe)"

if test -z "${debian_chroot:-}" && test -r "/etc/debian_chroot"; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

if ! echo "$HOME" | grep -q 'com.termux' ; then
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
fi

export DOTFILES="$HOME/dotfiles"
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

test -f "$HOME/.fzf.bash" && source "$HOME/.fzf.bash"

export VISUAL=vim
export EDITOR="$VISUAL"

# Virualenvs
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Envs
export ANDROID_HOME=$HOME/Android/Sdk

if test -d "$HOME/.pyenv"; then
  export PYENV_ROOT="$HOME/.pyenv"
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

test -f "$HOME/.config/broot/launcher/bash/br" && source "$HOME/.config/broot/launcher/bash/br"

test -f "$HOME/.cargo/env" && . "$HOME/.cargo/env"

test -f "$HOME/.rover/env" && source "$HOME/.rover/env"
test -n "$(type zoxide)" && eval "$(zoxide init bash)"
