[[verbs]]
execution = ":line_down"
key = "ctrl-alt-j"

[[verbs]]
execution = ":line_up"
key = "ctrl-alt-k"

[[verbs]]
execution = ":parent"
key = "alt-h"

[[verbs]]
execution = ":open_stay"
key = "alt-l"

[[verbs]]
execution = ":select_first"
key = "alt-g"

[[verbs]]
execution = ":back"
key = "alt-o"

[[verbs]]
execution = ":refresh"
key = "ctrl-r"
