PATH=/bin
PATH=$PATH:/sbin
PATH=$PATH:/usr/bin
PATH=$PATH:/usr/sbin
PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/local/sbin
PATH=$PATH:/usr/local/go/bin
PATH=$PATH:/usr/games
PATH=$PATH:/usr/local/games
PATH=$PATH:/snap/bin
PATH=$PATH:$HOME/go/bin
PATH=$PATH:$HOME/.cargo/bin
PATH=$PATH:$HOME/.cargo/bin
PATH=$PATH:$HOME/.cargo/bin
PATH=$PATH:$HOME/.cabal/bin
PATH=$PATH:$HOME/.ghcup/bin
PATH=$PATH:$HOME/.deno/bin
PATH=$PATH:$HOME/.bin
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/Android/Sdk/tools
PATH=$PATH:$HOME/Android/Sdk/emulator
PATH=$PATH:$HOME/Android/Sdk/tools/bin
PATH=$PATH:$HOME/Android/Sdk/platform-tools
PATH=$PATH:$HOME/.cache/depot_tools
PATH=$PATH:$HOME/.dotnet
PATH=$PATH:$HOME/.fzf/bin

export PATH=$PATH
