if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi
source ~/.install_dependencies
# Aliases
alias "python"="python3"
alias "pip"="pip3"
alias "bashrc"="vim ~/.bashrc"
alias "mkdir"="mkdir -pv"
alias "chr"="google-chrome"
alias "br"="brave-browser"
alias "co"="git add --all && git commit"
alias "pgAdmin4"="workon pgadmin4 ; python3.7 ~/.virtualenvs/pgadmin4/lib/python3.7/site-packages/pgadmin4/pgAdmin4.py"
alias "st"="clear; git status"
alias "south-pole"="ssh root@139.59.144.120"
alias "spectest-interp"="~/wabt/bin/spectest-interp"
alias "studio"="/usr/local/android-studio/bin/studio.sh"
alias "update-mouse"="sudo modprobe -r psmouse && sudo modprobe psmouse"
alias "wabt-unittests"="~/wabt/bin/wabt-unittests"
alias "wasm-interp"="~/wabt/bin/wasm-interp"
alias "wasm-objdump"="~/wabt/bin/wasm-objdump"
alias "wasm-opcodecnt"="~/wabt/bin/wasm-opcodecnt"
alias "wasm-validate"="~/wabt/bin/wasm-validate"
alias "wasm2c"="~/wabt/bin/wasm2c"
alias "wasm2wat"="~/wabt/bin/wasm2wat"
alias "wast2json"="~/wabt/bin/wast2json"
alias "wat-desugar"="~/wabt/bin/wat-desugar"
alias "wat2wasm"="~/wabt/bin/wat2wasm"
alias "trc"="vim ~/.tmux.conf"
alias "vrc"="vim ~/.vimrc"
alias "zrc"="vim ~/.zshrc"
alias "arc"="vim ~/.alacritty.yml"
alias "brc"="vim ~/.bashrc"
alias "zenv"="vim ~/.zshenv"
alias "irc"="vim ~/.install_dependencies"
alias "ta"="tmux-attach"

function tmux-attach() {
  tmux attach -t $1 
}

function translate() {
  directory=$(pwd)
  command cd ~/.fun_scraping
  pipenv run python wikipedia-translator.py "$1" "$2"
  command cd "$directory"
}
function anki() {
  directory=$(pwd)
  file="$directory"/"$1"
  echo File: "$file"
  command cd ~/.pyautogui
  pipenv run python anki.py "$file" "$2"
  command cd "$directory"
}

function tmux-start() {
  directory=$(pwd)
  cd ~/.pyautogui
  pipenv run python tmux.py "$1"
  cd "$directory"
}
alias "ts"="tmux-start"
fs() {
  local session
  session=$(tmux list-sessions -F "#{session_name}" | \
    fzf --query="$1" --select-1 --exit-0) &&
  tmux switch-client -t "$session"
}

function tmux() {
  emulate -L zsh

  # Make sure even pre-existing tmux sessions use the latest SSH_AUTH_SOCK.
  # (Inspired by: https://gist.github.com/lann/6771001)
  local SOCK_SYMLINK=~/.ssh/ssh_auth_sock
  if [ -r "$SSH_AUTH_SOCK" -a ! -L "$SSH_AUTH_SOCK" ]; then
    ln -sf "$SSH_AUTH_SOCK" $SOCK_SYMLINK
  fi

  # If provided with args, pass them through.
  if [[ -n "$@" ]]; then
    env SSH_AUTH_SOCK=$SOCK_SYMLINK tmux "$@"
    return
  fi

  # Check for .tmux file (poor man's Tmuxinator).
  if [ -x .tmux ]; then
    # Prompt the first time we see a given .tmux file before running it.
    local DIGEST="$(openssl sha256 .tmux)"
    if ! grep -q "$DIGEST" ~/..tmux.digests 2> /dev/null; then
      cat .tmux
      read -k 1 -r \
        'REPLY?Trust (and run) this .tmux file? (t = trust, otherwise = skip) '
      echo
      if [[ $REPLY =~ ^[Tt]$ ]]; then
        echo "$DIGEST" >> ~/..tmux.digests
        ./.tmux
        return
      fi
    else
      ./.tmux
      return
    fi
  fi

  # Attach to existing session, or create one, based on current directory.
  local SESSION_NAME=$(basename "${$(pwd)//[.:]/_}")
  env SSH_AUTH_SOCK=$SOCK_SYMLINK tmux new -A -s "$SESSION_NAME"
}

# Bounce the Dock icon, if iTerm does not have focus.
function bounce() {
  if [ -n "$TMUX" ]; then
    print -Pn "\ePtmux;\e\e]1337;RequestAttention=1\a\e\\"
  else
    print -Pn "\e]1337;RequestAttention=1\a"
  fi
}

alias "t"="tmux"
