#!/bin/zsh

export FZF_DEFAULT_OPTS="--preview 'preview {}'"
export DOTFILES="$HOME/dotfiles"

# Aliases
alias "q"="exit"
alias "$"=""
alias "so"="source"
alias "ac"="source ./.venv/bin/activate"
alias "ls"="my-ls"
alias "grep"='my-grep'
alias "da"="deactivate"

alias ssh="ssh -R 127.0.0.1:2222:127.0.0.1:22"

function scpb(){
    scp -r -P2222 "$1" rasmus@127.0.0.1:"$2"
}

function b {
    f=$(mktemp)
    (
  set +e
  broot --outcmd "$f" "$@"
  code=$?
  if [ "$code" != 0 ]; then
      rm -f "$f"
      exit "$code"
  fi
    )
    code=$?
    if [ "$code" != 0 ]; then
  return "$code"
    fi
    d=$(<"$f")
    rm -f "$f"
    eval "$d"
}

source ~/.paths.sh

if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi
