setopt histignorealldups sharehistory
setopt rm_star_silent

# Autosource https://github.com/seanyeh/autosrc
source $HOME/.autosrc.zsh

# Antigen

source $HOME/.zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# # Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Other Bundles
antigen bundle colored-man-pages
antigen bundle chrissicool/zsh-256color

# # Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

# diff-so-fancy
antigen bundle zdharma/zsh-diff-so-fancy

# # Tell Antigen that you're done.
antigen apply

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
  [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
  eval "$("$BASE16_SHELL/profile_helper.sh")"

# Vim mode
bindkey -v
set -o vi
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1

export HISTSIZE=100000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

# Use modern completion system
fpath=(~/.zsh_completions $fpath)
compdef g=git
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Plugins
bindkey '^ ' autosuggest-accept

export MANPAGER="/bin/sh -c \"unset PAGER;col -b -x | \
  v -R -c 'set ft=man nomod nolist' -c 'map q :q<CR>' \
  -c 'map <SPACE> <C-D>' -c 'map b <C-U>' \
  -c 'nmap K :Man <C-R>=expand(\\\"<cword>\\\")<CR><CR>' -\""

export GOPATH="${HOME}/go"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

# Virtualenvs
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=$(which python3.7)
export PROJECT_HOME=$HOME/Envs

if [ -f $HOME/.local/bin/virtualenvwrapper.sh ]
then 
  source $HOME/.local/bin/virtualenvwrapper.sh
fi

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Set default editor
if type "v" &> /dev/null;
then
  export VISUAL="v"
  alias "vim"="v"
else
  export VISUAL="v"
fi

export EDITOR="$VISUAL"

d="$HOME/.dircolors"
test -r $d && eval "$(dircolors -b $d)"

stty -ixon

autoload -U colors

RPROMPT_BASE="%F{blue}%~%f"
setopt PROMPT_SUBST

function preexec() {
  timer=$(($(date +%s%0N)/1000000))
}

function precmd() {
  if [ $timer ]; then
    now=$(($(date +%s%0N)/1000000))
    elapsed=$(($now-$timer))

    export RPROMPT="%F{cyan}${elapsed}ms %{$reset_color%} $RPROMPT_BASE"
    unset timer
  fi
}

# Anonymous function to avoid leaking NBSP variable.
function () {
  if [[ -n "$TMUX" ]]; then
    local LVL=$(($SHLVL - 1))
  else
    local LVL=$SHLVL
  fi
  if [[ $EUID -eq 0 ]]; then
    local SUFFIX=$(printf '#%.0s' {1..$LVL})
  else
    local SUFFIX=$(printf '\$%.0s' {1..$LVL})
  fi
  if [[ -n "$TMUX" ]]; then
    # Note use a non-breaking space at the end of the prompt because we can use it as
    # a find pattern to jump back in tmux.
    export PS1="%F{green}${SSH_TTY:+%n@%m}%f%B${SSH_TTY:+:}%b%F{blue}%1~%F{yellow}%B%(1j.*.)%(?..!)%b%f%F{red}%B${SUFFIX}%b%f › "
    export ZLE_RPROMPT_INDENT=0
  else
    # Don't bother with ZLE_RPROMPT_INDENT here, because it ends up eating the
    # space after PS1.
    export PS1="%F{green}${SSH_TTY:+%n@%m}%f%B${SSH_TTY:+:}%b%F{blue}%1~%F{yellow}%B%(1j.*.)%(?..!)%b%f%F{red}%B${SUFFIX}%b%f › "
  fi
}

export RPROMPT=$RPROMPT_BASE
export SPROMPT="zsh: correct %F{red}'%R'%f to %F{red}'%r'%f [%B%Uy%u%bes, %B%Un%u%bo, %B%Ue%u%bdit, %B%Ua%u%bbort]? "

DISABLE_AUTO_TITLE="true" # Don't rename tmux windows

[ -f $HOME/.config/broot/launcher/bash/br ] && source $HOME/.config/broot/launcher/bash/br
[ -f "/home/jrasmusbm/.ghcup/env" ] && source "/home/jrasmusbm/.ghcup/env" # ghcup-env

if test -d "$HOME/.pyenv" ; then
  export PYENV_ROOT="$HOME/.pyenv"
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

export FLYCTL_INSTALL="/home/jrasmusbm/.fly"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

_graphite_yargs_completions()
{
  si=$IFS
  IFS=$'
  ' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" graphite --get-yargs-completions "${words[@]}"))
  IFS="$si"
  _describe 'values' reply
}
compdef _graphite_yargs_completions graphite
compdef _graphite_yargs_completions gt

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

test -n "$(type zodide)" && eval "$(zoxide init zsh)"

# Speed-dial
bindkey -s "1" 'tmux-speeddial 1'
bindkey -s "2" 'tmux-speeddial 2'
bindkey -s "3" 'tmux-speeddial 3'
bindkey -s "4" 'tmux-speeddial 4'
bindkey -s "5" 'tmux-speeddial 5'
bindkey -s "6" 'tmux-speeddial 6'
bindkey -s "7" 'tmux-speeddial 7'
bindkey -s "8" 'tmux-speeddial 8'
bindkey -s "9" 'tmux-speeddial 9'
bindkey -s "0" 'tmux-speeddial 10'
bindkey -s "" 'ta all'
bindkey -s "" 'tk'
