" Most of this file is a direct copy of @ChrisToomey's vimrc. His organization
" really spoke to me so I decided that imitation is the greatest form of
" flattery.

if !has("nvim")
  set nocompatible
endif

" Need to set the leader before defining any leader mappings
let mapleader=";"
let maplocalleader="\<Space>"
" In case I am using Scandinavian Keyboard (Breaks most cases anyways)
nmap ö ;

function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

if !has('nvim')
  let g:plugin_path="~/.vim/bundle"
else
  let g:plugin_path="~/.local/share/nvim/plugged"
endif

call plug#begin(g:plugin_path)
call s:SourceConfigFilesIn("plugin_config")
Plug 'Olical/vim-enmasse'
call plug#end()

call s:SourceConfigFilesIn("other_config")
