packadd! vim-bushels

inoremap <leader><leader> <++>
inoremap <leader>dd :call bushels#delete_marker_row(1)
inoremap <leader>da :call bushels#delete_all_markers()
inoremap <leader>dm :call bushels#delete_marker(1)
nnoremap <leader>dd :call bushels#delete_marker_row(1)
nnoremap <leader>da :call bushels#delete_all_markers()
nnoremap <leader>dm :call bushels#delete_marker(1)
inoremap <leader>G :call bushels#backward_marker(1)
nnoremap <Leader>G :call bushels#backward_marker(1)
nnoremap 2<Leader>G :call bushels#backward_marker(2)
nnoremap 3<Leader>G :call bushels#backward_marker(3)
nnoremap 4<Leader>G :call bushels#backward_marker(4)
nnoremap 5<Leader>G :call bushels#backward_marker(5)
nnoremap 6<Leader>G :call bushels#backward_marker(6)
inoremap <leader>g :call bushels#forward_marker(1)
inoremap 2<leader>g :call bushels#forward_marker(2)
inoremap 3<leader>g :call bushels#forward_marker(3)
inoremap 4<leader>g :call bushels#forward_marker(4)
inoremap 5<leader>g :call bushels#forward_marker(5)
inoremap 6<leader>g :call bushels#forward_marker(6)
nnoremap <Leader>g :call bushels#forward_marker(1)
nnoremap 2<Leader>g :call bushels#forward_marker(2)
nnoremap 3<Leader>g :call bushels#forward_marker(3)
nnoremap 4<Leader>g :call bushels#forward_marker(4)
nnoremap 5<Leader>g :call bushels#forward_marker(5)
nnoremap 6<Leader>g :call bushels#forward_marker(6)
inoremap <leader>cp :call bushels#forward_marker(1).:call bushels#forward_marker(1)
