name:                my-xmonad
version:             0.1.0.0
github:              "githubuser/xmonad"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

dependencies:
- xmonad
- xmonad-contrib
- base >= 4.7 && < 5

library:
  source-dirs: src
