#!/bin/sh

set -e

_may_push() {
  branch_name="$(g branch --show-current)"

  if ! test "$branch_name" = "master" -o "$branch_name" = "main"; then
    return 0
  fi

  if ! confirm "You are on $branch_name, do you want to continue?"; then
    return 1
  fi

  return 0
}

if ! _may_push "$@" ; then
  exit 1
fi

g local-hook pre-commit
