#!/bin/sh

set -e

_supported_devices='DP-1-[1-3]'

if test "$(uname)" = 'Darwin' ; then
  grep_cmd='ggrep'
else
  grep_cmd='grep'
fi

_layout() {
  if test "$1" = 'supported'; then
    xrandr | "$grep_cmd" -qP "$_supported_devices connected"
    exit $?
  fi

  _screen_device="$(xrandr | awk "/$_supported_devices connected/ { print \$1 }")"

  if test "$1" = 'teardown'; then
    xrandr --output "$_screen_device" --off
    exit $?
  fi

  xrandr --output "$_screen_device" --auto --right-of eDP-1
}

_layout "$@"
