[colors.primary]
background = "0xf9f5d7"
foreground = "0x504945"

[colors.cursor]
text = "0xf9f5d7"
cursor = "0x504945"

[colors.normal]
black = "0xf9f5d7"
red = "0x9d0006"
green = "0x79740e"
yellow = "0xb57614"
blue = "0x076678"
magenta = "0x8f3f71"
cyan = "0x427b58"
white = "0x504945"

[colors.bright]
black = "0xbdae93"
red = "0x9d0006"
green = "0x79740e"
yellow = "0xb57614"
blue = "0x076678"
magenta = "0x8f3f71"
cyan = "0x427b58"
white = "0x282828"

[[colors.indexed_colors]]
index = 16
color = "0xaf3a03"

[[colors.indexed_colors]]
index = 17
color = "0xd65d0e"

[[colors.indexed_colors]]
index = 18
color = "0xebdbb2"

[[colors.indexed_colors]]
index = 19
color = "0xd5c4a1"

[[colors.indexed_colors]]
index = 20
color = "0x665c54"

[[colors.indexed_colors]]
index = 21
color = "0x3c3836"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"
