#!/bin/sh

_install_aws_vpn() {
  wget -q -O - https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo/awsvpnclient_public_key.asc | sudo apt-key add -
  echo "deb [arch=amd64] https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo ubuntu-20.04 main" | sudo tee /etc/apt/sources.list.d/aws-vpn-client.list
  sudo apt-get update
  sudo apt-get install awsvpnclient
  sudo ln -s /opt/awsvpnclient/AWS\ VPN\ Client /usr/local/bin/awsvpnclient
}

_install_aws_vpn "$@"
