#!/bin/sh

set -e


install_cs() {
  wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  sudo dpkg -i packages-microsoft-prod.deb
  sudo add-apt-repository universe
  sudo apt-get install -y apt-transport-https
  sudo apt-get update
  sudo apt-get install -y dotnet-sdk-2.2
  git clone git@github.com:uncrustify/uncrustify.git
  cd uncrustify
  configure
  make install
  cd ..
  rm -rf uncrustify
  sudo rm packages-microsoft-prod.deb
}

install_cs
