#!/bin/sh

set -e


_install_git_cli() {
  TEMP_DEB="$(mktemp)"
  GH_VERSION='2.5.1'
  wget -O "$TEMP_DEB" https://github.com/cli/cli/releases/download/v"$GH_VERSION"/gh_"$GH_VERSION"_linux_amd64.deb
  sudo dpkg -i "$TEMP_DEB"
  rm -f "$TEMP_DEB"
  gh config set editor "$DOTFILES/bin/nr --remote-wait-silent -c 'set filetype=gitcommit'"
}

_install_git_cli
