#!/bin/sh

install_git_extras() {
  TEMP_DEB="$(mktemp)"
  wget -O "$TEMP_DEB" "https://github.com/cli/cli/releases/download/v1.12.1/gh_1.12.1_linux_amd64.deb"
  sudo dpkg -i "$TEMP_DEB"
  rm -f "$TEMP_DEB"
  sudo apt-get install -y git-extras
}

install_git_extras
