#!/bin/sh

set -e


_install_golang() {
  (
    set -xe
    temp_dir="$(mktemp -d)"
    cd "$temp_dir" || return
    wget -O "golang.tar.gz" https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
    sudo rm -rf /usr/local/go
    sudo tar -C /usr/local -xzf "golang.tar.gz"
    rm -rf "$temp_dir"
  )
}

_install_golang
