#!/bin/sh

install_lua_language_server() {
  CURRENT_PATH=$(pwd)
  cd ~/.cache/
  git clone git@github.com:sumneko/lua-language-server.git
  cd lua-language-server
  git submodule update --init --recursive
  cd 3rd/luamake
  compile/install.sh
  cd ../..
  ./3rd/luamake/luamake rebuild
  cd $CURRENT_PATH
}

install_lua_language_server
