#!/bin/sh

set -e

_path="$HOME/.programs"

_install_node_debug2() {
  mkdir -p "$_path"
  (
    cd "$_path"

    if ! test -d vscode-node-debug2; then
      (
        git clone https://github.com/microsoft/vscode-node-debug2.git
      )
    fi

    cd vscode-node-debug2
    git pull

    npm install
    NODE_OPTIONS=--no-experimental-fetch npm run build
  )
}

_install_node_debug2 "$@"
