#!/bin/sh

install_nvim() {
  current=$(pwd)
  sudo apt-get install -y \
    build-essential \
    make \
    cmake \
    cmake-data \
    pkg-config \
    libtool-bin \
    automake \
    curl \
    gettext \
    zip
  rm -rf /tmp/nvim
  git clone git@github.com:neovim/neovim.git /tmp/nvim
  cd /tmp/nvim || return 1
  git checkout 4e352ecc42dc9c4ec0639007c13b03d5dceef619
  sudo make CMAKE_BUILD_TYPE=RelWithDebInfo
  sudo make install
  cd "$current" || return 1
  sudo rm -rf /tmp/nvim
  idep neovim_vm
}

install_nvim
