#!/bin/sh

set -e


install_nvim() {
  current=$(pwd)
  sudo apt-get install -y \
    build-essential \
    make \
    cmake \
    cmake-data \
    pkg-config \
    libtool-bin \
    automake \
    curl \
    gettext \
    zip
  temp_file="$(mktemp -d)"
  git clone git@github.com:neovim/neovim.git "$temp_file"
  cd "$temp_file" || return 1
  git switch -d 046950f6309070d98ab5a3deeff9d00e079ccdd4
  sudo make CMAKE_BUILD_TYPE=RelWithDebInfo
  sudo make install
  cd "$current" || return 1
  sudo rm -rf "$temp_file"
  idep neovim_vm
}

install_nvim
