#!/bin/bash

set -e


_install_postgres() {
  if test -z "$1"; then
    echo "Please supply a version!"
    exit 1
  fi

  sudo apt-get install curl ca-certificates gnupg
  curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  sudo apt-get update
  sudo apt install "postgresql-client-$1"
  pg_basebackup -V
}

_install_postgres "$@"
