#!/bin/sh

set -e


_install_python_dependencies () {
  sudo apt-get update -y; sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
    libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
  }

_install_pyenv() {
  _install_python_dependencies

  curl https://pyenv.run | bash

}

_install_pyenv "$@"
