#!/bin/sh

set -e


install_ripgrep() {
  TEMP_DEB="$(mktemp)"
  curl -L -o $TEMP_DEB https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
  sudo dpkg -i $TEMP_DEB
  rm $TEMP_DEB
}

install_ripgrep
