#!/bin/sh

set -e


install_spotify_cli() {
  sudo apt install -y \
    libncursesw5-dev \
    libdbus-1-dev \
    libpulse-dev \
    libssl-dev \
    libxcb1-dev \
    libxcb-render0-dev \
    libxcb-shape0-dev \
    libxcb-xfixes0-dev

  cargo install ncspot
}

install_spotify_cli
