#!/bin/sh

set -e


set -e

_install_terraform_ls() {
  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

  sudo apt-get update && sudo apt-get install terraform-ls
}

_install_terraform_ls "$@"
