#!/bin/sh

set -e


install_tmux() {
  sudo apt-get install -o Dpkg::Options::="--force-confnew" -y \
    automake \
    byacc \
    autoconf \
    build-essential \
    pkg-config \
    libevent-dev \
    libncurses5-dev
  current=$(pwd)
  sudo rm -rf /tmp/tmux
  git clone https://github.com/tmux/tmux.git /tmp/tmux
  cd /tmp/tmux
  git switch master
  sh autogen.sh
  ./configure && make
  sudo make install
  cd $current
  sudo rm -rf /tmp/tmux
}

install_tmux
