#!/bin/sh

set -e


_update() {
  sudo apt-get -y update
  sudo apt -y update
  sudo apt-get -y upgrade
  sudo apt -y upgrade
  sudo apt autoremove -y
  sudo apt-get autoremove -y
  sudo apt --fix-broken install -y
}

_update
