#!/bin/bash

set -e

current_dir=$(echo "${PWD##*/}" | tr '.' '_')

if ! tmux has-session -t="$current_dir" 2>/dev/null; then
  tmux new-session -d -s "$current_dir" -n run -x "$(tput cols)" -y "$(tput lines)"

  tmux new-window -n vim
  tmux send-keys -t vim "v -c GFiles" Enter

  tmux new-window -n cli
  tmux send-keys -t cli "g l" Enter
  tmux send-keys -t cli "g" Enter
fi

if test ! "$INITIATED_EXTERNALLY" = 'true'; then
  ta "$current_dir":vim
fi
