execute "source $DOTFILES/vim/snippets/css.vim"
execute "source $DOTFILES/vim/snippets/html.vim"
execute "source $DOTFILES/vim/snippets/javascript.vim"
execute "source $DOTFILES/vim/snippets/typescript.vim"
execute "source $DOTFILES/vim/snippets/graphql.vim"
